import { BlogPostArtifact } from '../artifacts/BlogPostArtifact';
import { CompetitorEvalArtifact } from '../artifacts/CompetitorEvalArtifact';
import { IncidentTriageArtifact } from '../artifacts/IncidentTriageArtifact';
import { LumenpathArtifact } from '../artifacts/LumenpathArtifact';
import { PrDiffArtifact } from '../artifacts/PrDiffArtifact';
import { ProductDecisionArtifact } from '../artifacts/ProductDecisionArtifact';
import { RfpProposalArtifact } from '../artifacts/RfpProposalArtifact';
import { SpaceInvadersArtifact } from '../artifacts/SpaceInvadersArtifact';
import type { Scenario } from './types';

/**
 * The eight authored scenarios that drive the landing demo player.
 *
 * Everything here is static and hand-written. Node graphs deliberately omit
 * `startedAt` (see types.ts) so the reused WorkflowGraphPanel renderer never
 * spins an ElapsedTimer interval. The player's run-token scheduler owns all time
 * and each node shows a static authored `duration` string instead.
 */
export const SCENARIOS: Scenario[] = [
  {
    id: 'product-feature',
    tabLabel: 'Product feature',
    tabHint: 'Engineering',
    title: 'Ship a product feature',
    subtitle: 'Software delivery · supervised orchestration',
    goal: 'Add a per-project API rate-limit setting with a migration, service enforcement, and tests.',
    credits: '19.4 AI credits',
    outcome: {
      goal: 'Introduce a configurable per-project API rate limit, enforced server-side and surfaced in project settings.',
      scope: [
        'Schema migration for a nullable rate_limit column',
        'Enforcement middleware with a 429 + Retry-After response',
        'Settings UI control and unit + integration tests',
      ],
      assumptions: [
        'Default remains unlimited when the value is null',
        'Limits are per-project, not per-key, for this iteration',
      ],
      review: ['Human review before merge. Nothing is deployed automatically'],
    },
    plan: [
      { id: 'p1', title: 'Design the setting & contract', owner: 'Morpheus', detail: 'Data shape, API surface, and enforcement semantics.' },
      { id: 'p2', title: 'Implement migration & middleware', owner: 'Tank', detail: 'Column, config plumbing, and the 429 path.' },
      { id: 'p3', title: 'Cover with tests', owner: 'Tank', detail: 'Unit tests for the limiter and an integration test.' },
      { id: 'p4', title: 'Document the setting', owner: 'Link', detail: 'Operator note in the project settings guide.' },
    ],
    nodes: [
      { id: 'coordinator', label: 'Coordinator', role: 'coordinator', agentRoleTitle: 'Coordinator', modelId: 'claude-sonnet-5', col: 0, row: 1.5 },
      { id: 'outcome', label: 'Outcome plan', role: 'outcome_plan', agentRoleTitle: 'Planning gate', col: 1, row: 1.5, duration: '9s' },
      { id: 'work-plan', label: 'Work plan', role: 'work_plan', agentRoleTitle: 'Work planning', col: 2, row: 1.5, duration: '7s' },
      { id: 'design', label: 'Design the setting & contract', role: 'agent', agentName: 'Morpheus', agentRoleTitle: 'Lead Architect', modelId: 'claude-opus-4.8', col: 3, row: 0.4, duration: '48s' },
      { id: 'build', label: 'Migration & enforcement', role: 'agent', agentName: 'Tank', agentRoleTitle: 'Core Implementer', modelId: 'claude-sonnet-5', pod: 'agentweaver-agent-host-bbkn5', col: 4, row: 0.9, duration: '2m 04s' },
      { id: 'tests', label: 'Limiter tests', role: 'agent', agentName: 'Tank', agentRoleTitle: 'Core Implementer', modelId: 'claude-sonnet-5', col: 4, row: 2.1, duration: '1m 12s' },
      { id: 'docs', label: 'Operator note', role: 'agent', agentName: 'Link', agentRoleTitle: 'Docs Writer', modelId: 'claude-sonnet-5', col: 3, row: 2.6, duration: '41s' },
      { id: 'review', label: 'Human review', role: 'review', agentRoleTitle: 'Human Review', col: 5, row: 1.5, isReviewGate: true },
    ],
    edges: [
      ['e-co', 'coordinator', 'outcome'],
      ['e-ow', 'outcome', 'work-plan'],
      ['e-wd', 'work-plan', 'design'],
      ['e-db', 'design', 'build'],
      ['e-bt', 'build', 'tests'],
      ['e-wdoc', 'work-plan', 'docs'],
      ['e-tr', 'tests', 'review'],
      ['e-dr', 'docs', 'review'],
    ],
    artifactLabel: 'Pull request preview',
    artifactCaption: 'The diff and checks a run like this opens.',
    Artifact: PrDiffArtifact,
  },
  {
    id: 'marketing',
    tabLabel: 'Marketing site',
    tabHint: 'Growth',
    title: 'Design a marketing launch page',
    subtitle: 'Brand & web · supervised orchestration',
    goal: 'Design a bold launch landing page for Lumenpath, an AI wayfinding product.',
    credits: '22.7 AI credits',
    outcome: {
      goal: 'Produce a striking, on-brand single-page launch site for Lumenpath with hero, features, pricing, and CTA.',
      scope: [
        'Art direction with a saturated, high-energy palette',
        'Hero, feature grid, pricing tiers, and closing CTA',
        'Responsive composition built from CSS and inline SVG',
      ],
      assumptions: [
        'Copy and pricing are placeholder inputs',
        'Distinct visual language from the Agentweaver frame is intended',
      ],
      review: ['Human review before anything is published'],
    },
    plan: [
      { id: 'p1', title: 'Set art direction', owner: 'Switch', detail: 'Palette, type, and mood that pop against a warm frame.' },
      { id: 'p2', title: 'Compose hero & narrative', owner: 'Switch', detail: 'Headline, nav, and above-the-fold composition.' },
      { id: 'p3', title: 'Build features & pricing', owner: 'Dozer', detail: 'Feature grid, three pricing tiers, and CTA band.' },
      { id: 'p4', title: 'Polish & QA copy', owner: 'Link', detail: 'Tighten voice and check contrast.' },
    ],
    nodes: [
      { id: 'coordinator', label: 'Coordinator', role: 'coordinator', agentRoleTitle: 'Coordinator', modelId: 'claude-sonnet-5', col: 0, row: 1.5 },
      { id: 'outcome', label: 'Outcome plan', role: 'outcome_plan', agentRoleTitle: 'Planning gate', col: 1, row: 1.5, duration: '8s' },
      { id: 'work-plan', label: 'Work plan', role: 'work_plan', agentRoleTitle: 'Work planning', col: 2, row: 1.5, duration: '6s' },
      { id: 'art', label: 'Set art direction', role: 'agent', agentName: 'Switch', agentRoleTitle: 'Brand Designer', modelId: 'claude-opus-4.8', col: 3, row: 0.4, duration: '55s' },
      { id: 'hero', label: 'Compose hero & narrative', role: 'agent', agentName: 'Switch', agentRoleTitle: 'Brand Designer', modelId: 'claude-opus-4.8', col: 4, row: 0.9, duration: '1m 22s' },
      { id: 'sections', label: 'Features & pricing', role: 'agent', agentName: 'Dozer', agentRoleTitle: 'Web Builder', modelId: 'claude-sonnet-5', col: 4, row: 2.1, duration: '1m 48s' },
      { id: 'copy', label: 'Polish & QA copy', role: 'agent', agentName: 'Link', agentRoleTitle: 'Copy Editor', modelId: 'claude-sonnet-5', col: 3, row: 2.6, duration: '38s' },
      { id: 'review', label: 'Human review', role: 'review', agentRoleTitle: 'Human Review', col: 5, row: 1.5, isReviewGate: true },
    ],
    edges: [
      ['e-co', 'coordinator', 'outcome'],
      ['e-ow', 'outcome', 'work-plan'],
      ['e-wa', 'work-plan', 'art'],
      ['e-ah', 'art', 'hero'],
      ['e-hs', 'hero', 'sections'],
      ['e-wc', 'work-plan', 'copy'],
      ['e-sr', 'sections', 'review'],
      ['e-cr', 'copy', 'review'],
    ],
    artifactLabel: 'Landing page preview',
    artifactCaption: 'A bold launch page in its own art direction.',
    Artifact: LumenpathArtifact,
  },
  {
    id: 'blog',
    tabLabel: 'Blog post',
    tabHint: 'Content',
    title: 'Write a standalone blog post',
    subtitle: 'Editorial · supervised orchestration',
    goal: 'Write a standalone blog post on why supervised agent orchestration beats autonomous swarms.',
    credits: '11.2 AI credits',
    outcome: {
      goal: 'Deliver one polished, standalone article, with no release notes, docs, or social bundle attached.',
      scope: [
        'A single well-structured long-form article',
        'Clear thesis, three supporting sections, and a close',
        'Editorial formatting: kicker, dropcap, pull-quote, tags',
      ],
      assumptions: [
        'Just the article is requested, with no companion assets',
        'Voice is opinionated but grounded',
      ],
      review: ['Human review before publishing'],
    },
    plan: [
      { id: 'p1', title: 'Outline the argument', owner: 'Oracle', detail: 'Thesis and the three beats that support it.' },
      { id: 'p2', title: 'Draft the article', owner: 'Link', detail: 'Full long-form draft with a strong open and close.' },
      { id: 'p3', title: 'Line edit', owner: 'Link', detail: 'Tighten rhythm, cut filler, format for reading.' },
    ],
    nodes: [
      { id: 'coordinator', label: 'Coordinator', role: 'coordinator', agentRoleTitle: 'Coordinator', modelId: 'claude-sonnet-5', col: 0, row: 1.5 },
      { id: 'outcome', label: 'Outcome plan', role: 'outcome_plan', agentRoleTitle: 'Planning gate', col: 1, row: 1.5, duration: '6s' },
      { id: 'work-plan', label: 'Work plan', role: 'work_plan', agentRoleTitle: 'Work planning', col: 2, row: 1.5, duration: '5s' },
      { id: 'outline', label: 'Outline the argument', role: 'agent', agentName: 'Oracle', agentRoleTitle: 'Editorial Lead', modelId: 'claude-opus-4.8', col: 3, row: 0.9, duration: '34s' },
      { id: 'draft', label: 'Draft the article', role: 'agent', agentName: 'Link', agentRoleTitle: 'Staff Writer', modelId: 'claude-sonnet-5', col: 4, row: 1.5, duration: '1m 31s' },
      { id: 'edit', label: 'Line edit', role: 'agent', agentName: 'Link', agentRoleTitle: 'Staff Writer', modelId: 'claude-sonnet-5', col: 3, row: 2.1, duration: '42s' },
      { id: 'review', label: 'Human review', role: 'review', agentRoleTitle: 'Human Review', col: 5, row: 1.5, isReviewGate: true },
    ],
    edges: [
      ['e-co', 'coordinator', 'outcome'],
      ['e-ow', 'outcome', 'work-plan'],
      ['e-wo', 'work-plan', 'outline'],
      ['e-od', 'outline', 'draft'],
      ['e-de', 'draft', 'edit'],
      ['e-er', 'edit', 'review'],
    ],
    artifactLabel: 'Article preview',
    artifactCaption: 'A standalone article page. Just the post, nothing bundled.',
    Artifact: BlogPostArtifact,
  },
  {
    id: 'incident',
    tabLabel: 'Incident triage',
    tabHint: 'Operations',
    title: 'Triage a production incident',
    subtitle: 'Reliability · supervised orchestration',
    goal: 'Triage a checkout latency spike: build an evidence timeline and propose remediation options.',
    credits: '14.8 AI credits',
    outcome: {
      goal: 'Produce a triage draft with an evidence-linked timeline and remediation options for a human to choose from.',
      scope: [
        'Correlate metrics, deploys, and traces into a timeline',
        'State a suspected cause with a confidence level',
        'Offer ranked remediation options, none auto-applied',
      ],
      assumptions: [
        'This is analysis only; no change is executed by the run',
        'A human on-call makes the remediation decision',
      ],
      review: ['Every remediation requires explicit human approval before it runs'],
    },
    plan: [
      { id: 'p1', title: 'Gather evidence', owner: 'Sentinel', detail: 'Pull metrics, recent deploys, and traces.' },
      { id: 'p2', title: 'Correlate a timeline', owner: 'Oracle', detail: 'Order events and isolate the blast radius.' },
      { id: 'p3', title: 'Draft remediation options', owner: 'Morpheus', detail: 'Rank reversible options with risk and recovery.' },
    ],
    nodes: [
      { id: 'coordinator', label: 'Coordinator', role: 'coordinator', agentRoleTitle: 'Coordinator', modelId: 'claude-sonnet-5', col: 0, row: 1.5 },
      { id: 'outcome', label: 'Outcome plan', role: 'outcome_plan', agentRoleTitle: 'Planning gate', col: 1, row: 1.5, duration: '7s' },
      { id: 'work-plan', label: 'Work plan', role: 'work_plan', agentRoleTitle: 'Work planning', col: 2, row: 1.5, duration: '5s' },
      { id: 'evidence', label: 'Gather evidence', role: 'agent', agentName: 'Sentinel', agentRoleTitle: 'Reliability Analyst', modelId: 'claude-sonnet-5', col: 3, row: 0.4, duration: '52s' },
      { id: 'timeline', label: 'Correlate a timeline', role: 'agent', agentName: 'Oracle', agentRoleTitle: 'Incident Lead', modelId: 'claude-opus-4.8', col: 4, row: 0.9, duration: '1m 08s' },
      { id: 'remediation', label: 'Draft remediation options', role: 'agent', agentName: 'Morpheus', agentRoleTitle: 'Lead Architect', modelId: 'claude-opus-4.8', col: 4, row: 2.1, duration: '58s' },
      { id: 'review', label: 'Human review', role: 'review', agentRoleTitle: 'Human Review', col: 5, row: 1.5, isReviewGate: true },
    ],
    edges: [
      ['e-co', 'coordinator', 'outcome'],
      ['e-ow', 'outcome', 'work-plan'],
      ['e-we', 'work-plan', 'evidence'],
      ['e-et', 'evidence', 'timeline'],
      ['e-tr2', 'timeline', 'remediation'],
      ['e-rr', 'remediation', 'review'],
    ],
    artifactLabel: 'Triage draft preview',
    artifactCaption: 'A triage draft with remediation options for review, never auto-applied.',
    Artifact: IncidentTriageArtifact,
  },
  {
    id: 'competitor',
    tabLabel: 'Vendor eval',
    tabHint: 'Strategy',
    title: 'Evaluate coding-agent vendors',
    subtitle: 'Technical strategy · supervised orchestration',
    goal: 'Compare GitHub Copilot, Cursor, Claude Code, and OpenAI Codex for a 60-engineer TS/.NET org.',
    credits: '16.1 AI credits',
    outcome: {
      goal: 'Build a weighted evaluation framework across four criteria with clearly sourced ratings.',
      scope: [
        'Criteria: repo understanding, enterprise controls, workflow fit, cost',
        'Transparent weights and a weighted-total per vendor',
        'Source notes with no fabricated vendor benchmarks',
      ],
      assumptions: [
        'Teams validate the ratings against their own pilot',
        'Scope is a 60-engineer TypeScript + .NET organization',
      ],
      review: ['Human review before this informs any purchasing decision'],
    },
    plan: [
      { id: 'p1', title: 'Define criteria & weights', owner: 'Oracle', detail: 'The four axes and how much each counts.' },
      { id: 'p2', title: 'Assemble source notes', owner: 'Sentinel', detail: 'Structured, clearly sourced notes.' },
      { id: 'p3', title: 'Score & synthesize', owner: 'Morpheus', detail: 'Apply weights and surface the trade-offs.' },
    ],
    nodes: [
      { id: 'coordinator', label: 'Coordinator', role: 'coordinator', agentRoleTitle: 'Coordinator', modelId: 'claude-sonnet-5', col: 0, row: 1.5 },
      { id: 'outcome', label: 'Outcome plan', role: 'outcome_plan', agentRoleTitle: 'Planning gate', col: 1, row: 1.5, duration: '8s' },
      { id: 'work-plan', label: 'Work plan', role: 'work_plan', agentRoleTitle: 'Work planning', col: 2, row: 1.5, duration: '6s' },
      { id: 'criteria', label: 'Define criteria & weights', role: 'agent', agentName: 'Oracle', agentRoleTitle: 'Strategy Lead', modelId: 'claude-opus-4.8', col: 3, row: 0.4, duration: '44s' },
      { id: 'notes', label: 'Assemble source notes', role: 'agent', agentName: 'Sentinel', agentRoleTitle: 'Research Analyst', modelId: 'claude-sonnet-5', col: 4, row: 0.9, duration: '1m 26s' },
      { id: 'score', label: 'Score & synthesize', role: 'agent', agentName: 'Morpheus', agentRoleTitle: 'Lead Architect', modelId: 'claude-opus-4.8', col: 4, row: 2.1, duration: '51s' },
      { id: 'review', label: 'Human review', role: 'review', agentRoleTitle: 'Human Review', col: 5, row: 1.5, isReviewGate: true },
    ],
    edges: [
      ['e-co', 'coordinator', 'outcome'],
      ['e-ow', 'outcome', 'work-plan'],
      ['e-wc2', 'work-plan', 'criteria'],
      ['e-cn', 'criteria', 'notes'],
      ['e-ns', 'notes', 'score'],
      ['e-sr2', 'score', 'review'],
    ],
    artifactLabel: 'Evaluation preview',
    artifactCaption: 'A weighted framework with sourced vendor ratings.',
    Artifact: CompetitorEvalArtifact,
  },
  {
    id: 'rfp',
    tabLabel: 'RFP response',
    tabHint: 'Proposals',
    title: 'Respond to an RFP',
    subtitle: 'Bid & proposal · supervised orchestration',
    goal: 'Draft an RFP response with a compliance matrix, technical approach, pricing, and a submission checklist.',
    credits: '20.3 AI credits',
    outcome: {
      goal: 'Assemble a polished proposal response covering compliance, approach, pricing narrative, and submission readiness.',
      scope: [
        'Requirement-by-requirement compliance matrix',
        'Phased technical approach and a pricing/budget narrative',
        'Submission checklist with an outstanding-items flag',
      ],
      assumptions: [
        'Requirements and figures are placeholder inputs',
        'A human owns the final submission decision',
      ],
      review: ['Human review before the response is submitted'],
    },
    plan: [
      { id: 'p1', title: 'Map the compliance matrix', owner: 'Sentinel', detail: 'Answer each requirement with a status and reference.' },
      { id: 'p2', title: 'Write the technical approach', owner: 'Morpheus', detail: 'Phased delivery with rollback gates.' },
      { id: 'p3', title: 'Build the pricing narrative', owner: 'Oracle', detail: 'Fixed-fee plus managed subscription with contingency.' },
      { id: 'p4', title: 'Assemble submission checklist', owner: 'Link', detail: 'Track volumes, signatures, and references.' },
    ],
    nodes: [
      { id: 'coordinator', label: 'Coordinator', role: 'coordinator', agentRoleTitle: 'Coordinator', modelId: 'claude-sonnet-5', col: 0, row: 1.5 },
      { id: 'outcome', label: 'Outcome plan', role: 'outcome_plan', agentRoleTitle: 'Planning gate', col: 1, row: 1.5, duration: '9s' },
      { id: 'work-plan', label: 'Work plan', role: 'work_plan', agentRoleTitle: 'Work planning', col: 2, row: 1.5, duration: '7s' },
      { id: 'matrix', label: 'Map the compliance matrix', role: 'agent', agentName: 'Sentinel', agentRoleTitle: 'Compliance Analyst', modelId: 'claude-sonnet-5', col: 3, row: 0.4, duration: '1m 03s' },
      { id: 'approach', label: 'Write the technical approach', role: 'agent', agentName: 'Morpheus', agentRoleTitle: 'Solution Lead', modelId: 'claude-opus-4.8', col: 4, row: 0.9, duration: '1m 34s' },
      { id: 'pricing', label: 'Build the pricing narrative', role: 'agent', agentName: 'Oracle', agentRoleTitle: 'Bid Manager', modelId: 'claude-opus-4.8', col: 4, row: 2.1, duration: '58s' },
      { id: 'checklist', label: 'Assemble submission checklist', role: 'agent', agentName: 'Link', agentRoleTitle: 'Proposal Coordinator', modelId: 'claude-sonnet-5', col: 3, row: 2.6, duration: '36s' },
      { id: 'review', label: 'Human review', role: 'review', agentRoleTitle: 'Human Review', col: 5, row: 1.5, isReviewGate: true },
    ],
    edges: [
      ['e-co', 'coordinator', 'outcome'],
      ['e-ow', 'outcome', 'work-plan'],
      ['e-wm', 'work-plan', 'matrix'],
      ['e-ma', 'matrix', 'approach'],
      ['e-ap', 'approach', 'pricing'],
      ['e-wch', 'work-plan', 'checklist'],
      ['e-pr', 'pricing', 'review'],
      ['e-chr', 'checklist', 'review'],
    ],
    artifactLabel: 'Proposal preview',
    artifactCaption: 'An RFP response with a compliance matrix and submission checklist.',
    Artifact: RfpProposalArtifact,
  },
  {
    id: 'game',
    tabLabel: 'Game scene',
    tabHint: 'Creative',
    title: 'Build a game splash scene',
    subtitle: 'Creative coding · supervised orchestration',
    goal: 'Create a Space Invaders-style splash scene: HUD, enemy rows, shields, and a player cannon.',
    credits: '9.6 AI credits',
    outcome: {
      goal: 'Render a non-playable arcade splash scene in SVG/CSS with a HUD, enemy formation, shields, and projectiles.',
      scope: [
        'HUD with score, high score, and lives',
        'Four enemy rows, defensive shields, and a player cannon',
        'Marching invaders and in-flight projectiles animated in CSS',
      ],
      assumptions: [
        'Visual demo only, with no game loop or input handling',
        'No focusable or interactive controls are included',
      ],
      review: ['Human review before it ships anywhere'],
    },
    plan: [
      { id: 'p1', title: 'Design the sprites', owner: 'Switch', detail: 'Invader, shield, and cannon shapes in SVG.' },
      { id: 'p2', title: 'Lay out the scene', owner: 'Dozer', detail: 'Formation, HUD, and projectile placement.' },
      { id: 'p3', title: 'Tune the palette', owner: 'Switch', detail: 'Arcade-neon colours on a dark field.' },
    ],
    nodes: [
      { id: 'coordinator', label: 'Coordinator', role: 'coordinator', agentRoleTitle: 'Coordinator', modelId: 'claude-sonnet-5', col: 0, row: 1.5 },
      { id: 'outcome', label: 'Outcome plan', role: 'outcome_plan', agentRoleTitle: 'Planning gate', col: 1, row: 1.5, duration: '5s' },
      { id: 'work-plan', label: 'Work plan', role: 'work_plan', agentRoleTitle: 'Work planning', col: 2, row: 1.5, duration: '4s' },
      { id: 'sprites', label: 'Design the sprites', role: 'agent', agentName: 'Switch', agentRoleTitle: 'Creative Coder', modelId: 'claude-opus-4.8', col: 3, row: 0.9, duration: '39s' },
      { id: 'scene', label: 'Lay out the scene', role: 'agent', agentName: 'Dozer', agentRoleTitle: 'Scene Builder', modelId: 'claude-sonnet-5', col: 4, row: 1.5, duration: '1m 07s' },
      { id: 'palette', label: 'Tune the palette', role: 'agent', agentName: 'Switch', agentRoleTitle: 'Creative Coder', modelId: 'claude-opus-4.8', col: 3, row: 2.1, duration: '28s' },
      { id: 'review', label: 'Human review', role: 'review', agentRoleTitle: 'Human Review', col: 5, row: 1.5, isReviewGate: true },
    ],
    edges: [
      ['e-co', 'coordinator', 'outcome'],
      ['e-ow', 'outcome', 'work-plan'],
      ['e-ws', 'work-plan', 'sprites'],
      ['e-ss', 'sprites', 'scene'],
      ['e-wp', 'work-plan', 'palette'],
      ['e-scr', 'scene', 'review'],
      ['e-pr2', 'palette', 'review'],
    ],
    artifactLabel: 'Game scene preview',
    artifactCaption: 'An animated, non-playable splash scene.',
    Artifact: SpaceInvadersArtifact,
  },
  {
    id: 'decision',
    tabLabel: 'Decision pack',
    tabHint: 'Product',
    title: 'Package a product decision',
    subtitle: 'Product strategy · supervised orchestration',
    goal: 'Should we launch a Team pricing tier? Synthesize PM, PMM, pricing, journeys, and a prototype.',
    credits: '24.9 AI credits',
    outcome: {
      goal: 'Synthesize a cross-functional decision pack for the Team-tier question with a clear recommendation.',
      scope: [
        'PM problem framing and market research',
        'PMM positioning, pricing scenarios, and user journeys',
        'A visual design prototype tying it together',
      ],
      assumptions: [
        'Figures and research are placeholder inputs',
        'The recommendation is advisory input for a human decision',
      ],
      review: ['Human review before any pricing change is committed'],
    },
    plan: [
      { id: 'p1', title: 'Frame the problem', owner: 'Oracle', detail: 'Demand signals, TAM, and the core risk.' },
      { id: 'p2', title: 'Position & price', owner: 'Switch', detail: 'Positioning statement and three pricing scenarios.' },
      { id: 'p3', title: 'Map user journeys', owner: 'Link', detail: 'From hitting the wall to collaborating as a team.' },
      { id: 'p4', title: 'Prototype the flow', owner: 'Dozer', detail: 'A wireframe of the Team workspace creation screen.' },
    ],
    nodes: [
      { id: 'coordinator', label: 'Coordinator', role: 'coordinator', agentRoleTitle: 'Coordinator', modelId: 'claude-sonnet-5', col: 0, row: 1.5 },
      { id: 'outcome', label: 'Outcome plan', role: 'outcome_plan', agentRoleTitle: 'Planning gate', col: 1, row: 1.5, duration: '9s' },
      { id: 'work-plan', label: 'Work plan', role: 'work_plan', agentRoleTitle: 'Work planning', col: 2, row: 1.5, duration: '7s' },
      { id: 'problem', label: 'Frame the problem', role: 'agent', agentName: 'Oracle', agentRoleTitle: 'Product Manager', modelId: 'claude-opus-4.8', col: 3, row: 0.4, duration: '58s' },
      { id: 'position', label: 'Position & price', role: 'agent', agentName: 'Switch', agentRoleTitle: 'Product Marketing', modelId: 'claude-opus-4.8', col: 4, row: 0.9, duration: '1m 12s' },
      { id: 'journeys', label: 'Map user journeys', role: 'agent', agentName: 'Link', agentRoleTitle: 'UX Writer', modelId: 'claude-sonnet-5', col: 4, row: 2.1, duration: '47s' },
      { id: 'proto', label: 'Prototype the flow', role: 'agent', agentName: 'Dozer', agentRoleTitle: 'Product Designer', modelId: 'claude-sonnet-5', col: 3, row: 2.6, duration: '1m 05s' },
      { id: 'review', label: 'Human review', role: 'review', agentRoleTitle: 'Human Review', col: 5, row: 1.5, isReviewGate: true },
    ],
    edges: [
      ['e-co', 'coordinator', 'outcome'],
      ['e-ow', 'outcome', 'work-plan'],
      ['e-wp2', 'work-plan', 'problem'],
      ['e-pp', 'problem', 'position'],
      ['e-pj', 'position', 'journeys'],
      ['e-wpr', 'work-plan', 'proto'],
      ['e-jr', 'journeys', 'review'],
      ['e-prr', 'proto', 'review'],
    ],
    artifactLabel: 'Decision pack preview',
    artifactCaption: 'A decision package that pulls together PM, PMM, pricing, journeys, and a prototype.',
    Artifact: ProductDecisionArtifact,
  },
];
