// <auto-generated />
using System;
using Agentweaver.Api.Memory;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Agentweaver.Api.Migrations
{
    [DbContext(typeof(MemoryDbContext))]
    partial class MemoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("Agentweaver.Api.Auth.OAuth.EntraOAuthState", b =>
                {
                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodeVerifier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.HasKey("State");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("EntraOAuthStates");
                });

            modelBuilder.Entity("Agentweaver.Api.Auth.OAuth.McpAuthorizationCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodeChallenge")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GithubLogin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RedirectUri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ExpiresAt");

                    b.ToTable("McpAuthorizationCodes");
                });

            modelBuilder.Entity("Agentweaver.Api.Auth.OAuth.McpClientRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientName")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RedirectUris")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("McpClientRegistrations");
                });

            modelBuilder.Entity("Agentweaver.Api.Auth.OAuth.McpPendingAuthorization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientState")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodeChallenge")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RedirectUri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Resource")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("State")
                        .IsUnique();

                    b.ToTable("McpPendingAuthorizations");
                });

            modelBuilder.Entity("Agentweaver.Api.Auth.OAuth.McpRefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AbsoluteExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChainId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GithubLogin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Org")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChainId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("Subject", "ClientId");

                    b.ToTable("McpRefreshTokens");
                });

            modelBuilder.Entity("Agentweaver.Api.Auth.OAuth.McpRevokedJti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Jti")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Jti")
                        .IsUnique();

                    b.ToTable("McpRevokedJtis");
                });

            modelBuilder.Entity("Agentweaver.Api.Auth.OAuth.OAuthState", b =>
                {
                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.HasKey("State");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("OAuthStates");
                });

            modelBuilder.Entity("Agentweaver.Api.Auth.OAuth.WebSessionExchangeCode", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("WebSessionExchangeCodes");
                });

            modelBuilder.Entity("Agentweaver.Api.Coordinator.CoordinatorAssemblyReviewRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AggregateTreeHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CoordinatorFailedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoordinatorFailureReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoordinatorRunId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DecisionSubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IntegrationBranch")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerUser")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reviewer")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CoordinatorRunId")
                        .IsUnique();

                    b.ToTable("AssemblyReviews");
                });

            modelBuilder.Entity("Agentweaver.Api.Diagnostics.HeartbeatStatusRecord", b =>
                {
                    b.Property<string>("PodName")
                        .HasColumnType("TEXT");

                    b.Property<int>("ActedCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastTickUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("PodName");

                    b.ToTable("HeartbeatStatuses");
                });

            modelBuilder.Entity("Agentweaver.Api.Memory.AgentMemory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Importance")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceIdentity")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("legacy");

                    b.Property<string>("SourceRunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrustState")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("legacy");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "AgentName");

                    b.HasIndex("ProjectId", "Type");

                    b.ToTable("AgentMemory");
                });

            modelBuilder.Entity("Agentweaver.Api.Memory.AuthModeEpochRecord", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("AuthMode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("auth_mode");

                    b.Property<long>("Epoch")
                        .HasColumnType("INTEGER")
                        .HasColumnName("epoch");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Key");

                    b.ToTable("auth_mode_epochs", (string)null);
                });

            modelBuilder.Entity("Agentweaver.Api.Memory.Decision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rationale")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceIdentity")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("legacy");

                    b.Property<string>("SourceRunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SupersededById")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrustState")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("legacy");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SupersededById");

                    b.HasIndex("ProjectId", "AgentName");

                    b.HasIndex("ProjectId", "Status");

                    b.ToTable("Decisions");
                });

            modelBuilder.Entity("Agentweaver.Api.Memory.DecisionInboxEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DecisionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("MergedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rationale")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceIdentity")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("legacy");

                    b.Property<string>("SourceRunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DecisionId");

                    b.HasIndex("ProjectId", "Slug")
                        .IsUnique();

                    b.HasIndex("ProjectId", "Status");

                    b.ToTable("DecisionInbox");
                });

            modelBuilder.Entity("Agentweaver.Api.Memory.DismissedNotification", b =>
                {
                    b.Property<string>("User")
                        .HasColumnType("TEXT")
                        .HasColumnName("user");

                    b.Property<string>("NotificationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("notification_id");

                    b.Property<DateTimeOffset>("DismissedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("dismissed_at");

                    b.HasKey("User", "NotificationId");

                    b.ToTable("dismissed_notifications", (string)null);
                });

            modelBuilder.Entity("Agentweaver.Api.Memory.GitHubAccountLinkStateRecord", b =>
                {
                    b.Property<string>("State")
                        .HasColumnType("TEXT")
                        .HasColumnName("state");

                    b.Property<string>("EntraUserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("entra_user_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.HasKey("State");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("github_account_link_states", (string)null);
                });

            modelBuilder.Entity("Agentweaver.Api.Memory.IntegrationBuildLockRecord", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AcquiredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerPodId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectId");

                    b.ToTable("IntegrationBuildLocks");
                });

            modelBuilder.Entity("Agentweaver.Api.Memory.OutcomeSpec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowTaskPromotion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Assumptions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClarifyingQuestions")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfirmedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoordinatorRunId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DesiredOutcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "CoordinatorRunId");

                    b.ToTable("OutcomeSpecs");
                });

            modelBuilder.Entity("Agentweaver.Api.Memory.ProjectGitHubIdentityOverrideRecord", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<string>("EntraUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("entra_user_id");

                    b.Property<string>("GitHubLogin")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("github_login");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("ProjectId", "EntraUserId");

                    b.HasIndex("EntraUserId", "GitHubLogin")
                        .HasDatabaseName("IX_project_github_identity_overrides_user_login");

                    b.ToTable("project_github_identity_overrides", (string)null);
                });

            modelBuilder.Entity("Agentweaver.Api.Memory.RunAuthorshipCapability", b =>
                {
                    b.Property<string>("RunId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("run_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("token_hash");

                    b.HasKey("RunId");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("run_authorship_capabilities", (string)null);
                });

            modelBuilder.Entity("Agentweaver.Api.Memory.SessionContext", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActiveIssues")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FocusArea")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SerializedState")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "EndedAt");

                    b.HasIndex("ProjectId", "SessionId")
                        .IsUnique();

                    b.ToTable("SessionContexts");
                });

            modelBuilder.Entity("Agentweaver.Api.Memory.SteeringDirective", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActionAttempt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoordinatorRunId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DecidedAction")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ExecStartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExecutionAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RelayedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetChildRunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetScopeJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("TreeHash")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CoordinatorRunId", "Status");

                    b.ToTable("SteeringDirectives");
                });

            modelBuilder.Entity("Agentweaver.Api.Memory.SteeringRevisionExecution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActionAttempt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CheckpointWatermark")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EffectState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SteeringDirectiveId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SteeringDirectiveId", "ActionAttempt", "RunId")
                        .IsUnique();

                    b.ToTable("SteeringRevisionExecutions");
                });

            modelBuilder.Entity("Agentweaver.Api.Memory.Subtask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentCharter")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedAgent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChildRunId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeclaredOutputPathsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InfrastructureRetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("InfrastructureRetryEligibleAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IsolationStrategy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastResetAttempt")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastResetDirectiveId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LockedOutAgents")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PriorChildRunId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecoveryAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecoveryGuidance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedModelId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("SteeringRetentionUntil")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkPlanId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkPlanId");

                    b.ToTable("Subtasks");
                });

            modelBuilder.Entity("Agentweaver.Api.Memory.SubtaskDependency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DependsOnSubtaskId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubtaskId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DependsOnSubtaskId");

                    b.HasIndex("SubtaskId");

                    b.ToTable("SubtaskDependencies");
                });

            modelBuilder.Entity("Agentweaver.Api.Memory.WorkPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssemblyStage")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("AssemblyStartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssemblyStatusReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssemblyTerminalStage")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoordinatorPodId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoordinatorRunId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("HumanReviewRoundTrips")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IntegrationBranch")
                        .HasColumnType("TEXT");

                    b.Property<string>("IsolationSummary")
                        .HasColumnType("TEXT");

                    b.Property<int>("OutcomeSpecId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SteeringIterations")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CoordinatorRunId");

                    b.HasIndex("OutcomeSpecId");

                    b.ToTable("WorkPlans");
                });

            modelBuilder.Entity("Agentweaver.Api.Runs.CoordinatorDeferredDecisionRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunId")
                        .IsUnique();

                    b.ToTable("DeferredDecisions");
                });

            modelBuilder.Entity("Agentweaver.Api.Runs.PendingRequestRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerUser")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("RunId")
                        .IsUnique();

                    b.ToTable("PendingRequests");
                });

            modelBuilder.Entity("Agentweaver.Api.Runs.RunEventRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.HasIndex("RunId", "Sequence")
                        .IsUnique();

                    b.ToTable("RunEvents");
                });

            modelBuilder.Entity("Agentweaver.Api.Memory.Decision", b =>
                {
                    b.HasOne("Agentweaver.Api.Memory.Decision", null)
                        .WithMany()
                        .HasForeignKey("SupersededById");
                });

            modelBuilder.Entity("Agentweaver.Api.Memory.DecisionInboxEntry", b =>
                {
                    b.HasOne("Agentweaver.Api.Memory.Decision", null)
                        .WithMany()
                        .HasForeignKey("DecisionId");
                });

            modelBuilder.Entity("Agentweaver.Api.Memory.Subtask", b =>
                {
                    b.HasOne("Agentweaver.Api.Memory.WorkPlan", null)
                        .WithMany()
                        .HasForeignKey("WorkPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Agentweaver.Api.Memory.SubtaskDependency", b =>
                {
                    b.HasOne("Agentweaver.Api.Memory.Subtask", null)
                        .WithMany()
                        .HasForeignKey("DependsOnSubtaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Agentweaver.Api.Memory.Subtask", null)
                        .WithMany()
                        .HasForeignKey("SubtaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Agentweaver.Api.Memory.WorkPlan", b =>
                {
                    b.HasOne("Agentweaver.Api.Memory.OutcomeSpec", null)
                        .WithMany()
                        .HasForeignKey("OutcomeSpecId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
