apiVersion: approuting.kubernetes.azure.com/v1alpha1
kind: DefaultDomainCertificate
metadata:
  name: identity-broker
  namespace: agentweaver-v1-p0
  labels:
    agentweaver.io/service: identity-broker
spec:
  target:
    secret: identity-broker-tls
