// <auto-generated />
using System;
using Agentweaver.Projects.Config;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Agentweaver.Projects.Config.Migrations
{
    [DbContext(typeof(ProjectsConfigDbContext))]
    [Migration("20261006095348_InitialProjectsConfig")]
    partial class InitialProjectsConfig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("projects_config")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Agentweaver.Projects.Config.PlatformRuntimeHeadRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("id");

                    b.Property<long>("CurrentRevision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("current_revision");

                    b.HasKey("Id");

                    b.ToTable("platform_runtime_heads", "projects_config", t =>
                        {
                            t.HasCheckConstraint("ck_platform_runtime_singleton", "id = 'default'");
                        });

                    b.HasData(
                        new
                        {
                            Id = "default",
                            CurrentRevision = 0L
                        });
                });

            modelBuilder.Entity("Agentweaver.Projects.Config.PlatformRuntimeRevisionRecord", b =>
                {
                    b.Property<long>("Revision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Revision"));

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("configuration");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("HeadId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("head_id");

                    b.Property<string>("UpdatedByActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by_actor_id");

                    b.HasKey("Revision");

                    b.HasIndex("HeadId");

                    b.ToTable("platform_runtime_revisions", "projects_config");
                });

            modelBuilder.Entity("Agentweaver.Projects.Config.ProjectConfigurationRevisionRecord", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("project_id");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("configuration");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("UpdatedByActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by_actor_id");

                    b.HasKey("ProjectId", "Revision");

                    b.ToTable("project_configuration_revisions", "projects_config");
                });

            modelBuilder.Entity("Agentweaver.Projects.Config.ProjectRecord", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("project_id");

                    b.Property<long>("ConfigurationRevision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("configuration_revision");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("OwnerActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("owner_actor_id");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("state");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ProjectId");

                    b.HasIndex("TenantId", "OwnerActorId", "State");

                    b.ToTable("projects", "projects_config", t =>
                        {
                            t.HasCheckConstraint("ck_projects_configuration_revision", "configuration_revision > 0");

                            t.HasCheckConstraint("ck_projects_revision", "revision > 0");

                            t.HasCheckConstraint("ck_projects_state", "state IN ('Active', 'Archived')");
                        });
                });

            modelBuilder.Entity("Agentweaver.Projects.Config.ProjectRunSelectionRecord", b =>
                {
                    b.Property<string>("RunId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("run_id");

                    b.Property<string>("ContextRevision")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("context_revision");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("PlatformRuntimeRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("platform_runtime_revision");

                    b.Property<long>("ProjectConfigurationRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("project_configuration_revision");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("project_id");

                    b.Property<long>("ProjectRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("project_revision");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_fingerprint");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("snapshot");

                    b.HasKey("RunId");

                    b.HasIndex("ProjectId", "RunId")
                        .IsUnique();

                    b.ToTable("project_run_selections", "projects_config");
                });

            modelBuilder.Entity("Agentweaver.Projects.Config.PlatformRuntimeRevisionRecord", b =>
                {
                    b.HasOne("Agentweaver.Projects.Config.PlatformRuntimeHeadRecord", null)
                        .WithMany()
                        .HasForeignKey("HeadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Agentweaver.Projects.Config.ProjectConfigurationRevisionRecord", b =>
                {
                    b.HasOne("Agentweaver.Projects.Config.ProjectRecord", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Agentweaver.Projects.Config.ProjectRunSelectionRecord", b =>
                {
                    b.HasOne("Agentweaver.Projects.Config.ProjectRecord", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
