// <auto-generated />
using System;
using Agentweaver.Projects.Config;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Agentweaver.Projects.Config.Migrations
{
    [DbContext(typeof(ProjectsConfigDbContext))]
    [Migration("20261009015456_AddMarketplaceSources")]
    partial class AddMarketplaceSources
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("projects_config")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Agentweaver.Projects.Config.PlatformRuntimeHeadRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("id");

                    b.Property<long>("CurrentRevision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("current_revision");

                    b.HasKey("Id");

                    b.ToTable("platform_runtime_heads", "projects_config", t =>
                        {
                            t.HasCheckConstraint("ck_platform_runtime_singleton", "id = 'default'");
                        });

                    b.HasData(
                        new
                        {
                            Id = "default",
                            CurrentRevision = 0L
                        });
                });

            modelBuilder.Entity("Agentweaver.Projects.Config.PlatformRuntimeRevisionRecord", b =>
                {
                    b.Property<long>("Revision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Revision"));

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("configuration");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("HeadId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("head_id");

                    b.Property<string>("UpdatedByActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by_actor_id");

                    b.HasKey("Revision");

                    b.HasIndex("HeadId");

                    b.ToTable("platform_runtime_revisions", "projects_config");
                });

            modelBuilder.Entity("Agentweaver.Projects.Config.ProjectAuthorityAuditRecord", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor");

                    b.Property<Guid?>("AssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("event_type");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("issuer");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("membership_id");

                    b.Property<string>("ResourceId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("resource_type");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<string>("Role")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("subject");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("tenant_id");

                    b.HasKey("EventId");

                    b.HasIndex("MembershipId", "CreatedAt");

                    b.ToTable("authority_audit", "projects_config", t =>
                        {
                            t.HasCheckConstraint("ck_authority_audit_event_type", "event_type IN ('membership_granted', 'membership_revoked', 'role_assigned', 'role_revoked')");

                            t.HasCheckConstraint("ck_authority_audit_revision", "revision > 0");
                        });
                });

            modelBuilder.Entity("Agentweaver.Projects.Config.ProjectConfigurationRevisionRecord", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("project_id");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("configuration");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("UpdatedByActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by_actor_id");

                    b.HasKey("ProjectId", "Revision");

                    b.ToTable("project_configuration_revisions", "projects_config");
                });

            modelBuilder.Entity("Agentweaver.Projects.Config.ProjectMarketplaceSourceRecord", b =>
                {
                    b.Property<Guid>("SourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by_actor_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("normalized_name");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("project_id");

                    b.Property<string>("Repository")
                        .IsRequired()
                        .HasMaxLength(201)
                        .HasColumnType("character varying(201)")
                        .HasColumnName("repository");

                    b.Property<string>("RequestedRef")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("requested_ref");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("state");

                    b.Property<string>("Subpath")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("subpath");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedByActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by_actor_id");

                    b.HasKey("SourceId");

                    b.HasIndex("ProjectId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_marketplace_sources_project_name_active")
                        .HasFilter("\"state\" = 'Active'");

                    b.HasIndex("ProjectId", "State");

                    b.ToTable("marketplace_sources", "projects_config", t =>
                        {
                            t.HasCheckConstraint("ck_marketplace_sources_revision", "revision > 0");

                            t.HasCheckConstraint("ck_marketplace_sources_state", "state IN ('Active', 'Removed')");
                        });
                });

            modelBuilder.Entity("Agentweaver.Projects.Config.ProjectRecord", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("project_id");

                    b.Property<long>("ConfigurationRevision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("configuration_revision");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by_actor_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("state");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ProjectId");

                    b.HasIndex("TenantId", "State");

                    b.ToTable("projects", "projects_config", t =>
                        {
                            t.HasCheckConstraint("ck_projects_configuration_revision", "configuration_revision > 0");

                            t.HasCheckConstraint("ck_projects_revision", "revision > 0");

                            t.HasCheckConstraint("ck_projects_state", "state IN ('Active', 'Archived')");
                        });
                });

            modelBuilder.Entity("Agentweaver.Projects.Config.ProjectRoleAssignmentRecord", b =>
                {
                    b.Property<Guid>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<string>("GrantedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("granted_by");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("membership_id");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("resource_type");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("revoked_by");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("state");

                    b.HasKey("AssignmentId");

                    b.HasIndex("MembershipId", "ResourceType", "ResourceId", "Role")
                        .IsUnique()
                        .HasFilter("\"state\" = 'Active'");

                    b.HasIndex("ResourceType", "ResourceId", "Role", "State");

                    b.ToTable("project_role_assignments", "projects_config", t =>
                        {
                            t.HasCheckConstraint("ck_project_role_assignments_resource_type", "resource_type IN ('Platform', 'Tenant', 'Project')");

                            t.HasCheckConstraint("ck_project_role_assignments_revision", "revision > 0");

                            t.HasCheckConstraint("ck_project_role_assignments_role", "role IN ('PlatformAdmin', 'TenantAdmin', 'Owner', 'Contributor', 'Viewer', 'Orchestrator')");

                            t.HasCheckConstraint("ck_project_role_assignments_state", "state IN ('Active', 'Revoked')");
                        });
                });

            modelBuilder.Entity("Agentweaver.Projects.Config.ProjectRunSelectionRecord", b =>
                {
                    b.Property<string>("RunId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("run_id");

                    b.Property<string>("ContextRevision")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("context_revision");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("PlatformRuntimeRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("platform_runtime_revision");

                    b.Property<long>("ProjectConfigurationRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("project_configuration_revision");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("project_id");

                    b.Property<long>("ProjectRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("project_revision");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_fingerprint");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("snapshot");

                    b.HasKey("RunId");

                    b.HasIndex("ProjectId", "RunId")
                        .IsUnique();

                    b.ToTable("project_run_selections", "projects_config");
                });

            modelBuilder.Entity("Agentweaver.Projects.Config.ProjectTenantMembershipRecord", b =>
                {
                    b.Property<Guid>("MembershipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("membership_id");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<string>("GrantedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("granted_by");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("issuer");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("revoked_by");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("state");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("subject");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("tenant_id");

                    b.HasKey("MembershipId");

                    b.HasIndex("Issuer", "Subject", "State");

                    b.HasIndex("Issuer", "Subject", "TenantId")
                        .IsUnique()
                        .HasFilter("\"state\" = 'Active'");

                    b.ToTable("tenant_memberships", "projects_config", t =>
                        {
                            t.HasCheckConstraint("ck_tenant_memberships_revision", "revision > 0");

                            t.HasCheckConstraint("ck_tenant_memberships_state", "state IN ('Active', 'Revoked')");
                        });
                });

            modelBuilder.Entity("Agentweaver.Projects.Config.PlatformRuntimeRevisionRecord", b =>
                {
                    b.HasOne("Agentweaver.Projects.Config.PlatformRuntimeHeadRecord", null)
                        .WithMany()
                        .HasForeignKey("HeadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Agentweaver.Projects.Config.ProjectConfigurationRevisionRecord", b =>
                {
                    b.HasOne("Agentweaver.Projects.Config.ProjectRecord", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Agentweaver.Projects.Config.ProjectMarketplaceSourceRecord", b =>
                {
                    b.HasOne("Agentweaver.Projects.Config.ProjectRecord", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Agentweaver.Projects.Config.ProjectRoleAssignmentRecord", b =>
                {
                    b.HasOne("Agentweaver.Projects.Config.ProjectTenantMembershipRecord", null)
                        .WithMany()
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Agentweaver.Projects.Config.ProjectRunSelectionRecord", b =>
                {
                    b.HasOne("Agentweaver.Projects.Config.ProjectRecord", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
