// <auto-generated />
using System;
using Agentweaver.Identity.Broker;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Agentweaver.Identity.Broker.Migrations
{
    [DbContext(typeof(IdentityBrokerDbContext))]
    [Migration("20261010150712_AddRemoteMcpOAuthConsentEndpoints")]
    partial class AddRemoteMcpOAuthConsentEndpoints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity_broker")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Agentweaver.Identity.Broker.BrokerUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("Issuer", "Subject")
                        .IsUnique();

                    b.ToTable("broker_users", "identity_broker");
                });

            modelBuilder.Entity("Agentweaver.Identity.Broker.CopilotConnectionRecord", b =>
                {
                    b.Property<Guid>("ConnectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CredentialKind")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("FreshUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GitHubUserId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("OwnerActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("OwnerIssuer")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<int>("Scope")
                        .HasColumnType("integer");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SecretId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SecretVersion")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("StateHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("ConnectionId");

                    b.ToTable("copilot_connections", "identity_broker");
                });

            modelBuilder.Entity("Agentweaver.Identity.Broker.CopilotConnectionRevision", b =>
                {
                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("FreshUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecretId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SecretVersion")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("ConnectionId", "Revision");

                    b.ToTable("copilot_connection_revisions", "identity_broker");
                });

            modelBuilder.Entity("Agentweaver.Identity.Broker.PendingAuthorization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("CodeChallenge")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("CodeChallengeMethod")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HandleHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Nonce")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ProjectId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("RedirectUri")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("RunId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("State")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<Guid?>("SubjectUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("HandleHash")
                        .IsUnique();

                    b.ToTable("pending_authorizations", "identity_broker");
                });

            modelBuilder.Entity("Agentweaver.Identity.Broker.RemoteMcpOAuthConnectionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AccessTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("access_token_expires_at");

                    b.Property<string>("AccessTokenSecretId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("access_token_secret_id");

                    b.Property<string>("AccessTokenSecretVersion")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("access_token_secret_version");

                    b.Property<string>("BindingHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("binding_hash")
                        .IsFixedLength();

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("client_id");

                    b.Property<long>("ConfigurationRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("configuration_revision");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("connection_id");

                    b.Property<long>("ConnectionRevision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("connection_revision");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CredentialRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("credential_revision");

                    b.Property<string>("EndpointUri")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("endpoint_uri");

                    b.Property<string>("EnvironmentConfigurationHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("environment_configuration_hash")
                        .IsFixedLength();

                    b.Property<string>("IdentityBindingReference")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character(32)")
                        .HasColumnName("identity_binding_reference")
                        .IsFixedLength();

                    b.Property<string>("IssuerUri")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("issuer_uri");

                    b.Property<string>("LastDisconnectIdempotencyHash")
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("last_disconnect_idempotency_hash")
                        .IsFixedLength();

                    b.Property<string>("LastDisconnectRequestHash")
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("last_disconnect_request_hash")
                        .IsFixedLength();

                    b.Property<long?>("LastDisconnectResultRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("last_disconnect_result_revision");

                    b.Property<string>("OwnerActorId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("owner_actor_id");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("OwnerIssuer")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("owner_issuer");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("project_id");

                    b.Property<string>("RedirectUri")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("redirect_uri");

                    b.Property<Guid?>("RefreshAttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("refresh_attempt_id");

                    b.Property<DateTimeOffset?>("RefreshStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_started_at");

                    b.Property<DateTimeOffset?>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expires_at");

                    b.Property<string>("RefreshTokenSecretId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("refresh_token_secret_id");

                    b.Property<string>("RefreshTokenSecretVersion")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("refresh_token_secret_version");

                    b.Property<string>("ResourceUri")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("resource_uri");

                    b.Property<string>("ScopesJson")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("scopes_json");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TransportProfile")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("transport_profile");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IdentityBindingReference")
                        .IsUnique();

                    b.HasIndex("OwnerId", "TenantId", "ProjectId", "ConnectionId")
                        .IsUnique();

                    b.ToTable("remote_mcp_oauth_connections", "identity_broker", t =>
                        {
                            t.HasCheckConstraint("ck_remote_mcp_oauth_connection_disconnect", "(last_disconnect_idempotency_hash IS NULL) = (last_disconnect_request_hash IS NULL) AND (last_disconnect_idempotency_hash IS NULL) = (last_disconnect_result_revision IS NULL)");

                            t.HasCheckConstraint("ck_remote_mcp_oauth_connection_hashes", "environment_configuration_hash ~ '^[0-9a-f]{64}$' AND binding_hash ~ '^[0-9a-f]{64}$' AND (last_disconnect_idempotency_hash IS NULL OR last_disconnect_idempotency_hash ~ '^[0-9a-f]{64}$') AND (last_disconnect_request_hash IS NULL OR last_disconnect_request_hash ~ '^[0-9a-f]{64}$')");

                            t.HasCheckConstraint("ck_remote_mcp_oauth_connection_refs", "(access_token_secret_id IS NULL) = (access_token_secret_version IS NULL) AND (access_token_secret_id IS NULL) = (access_token_expires_at IS NULL) AND (refresh_token_secret_id IS NULL) = (refresh_token_secret_version IS NULL) AND (refresh_token_secret_id IS NOT NULL OR refresh_token_expires_at IS NULL)");

                            t.HasCheckConstraint("ck_remote_mcp_oauth_connection_revisions", "configuration_revision > 0 AND connection_revision > 0 AND credential_revision >= 0");

                            t.HasCheckConstraint("ck_remote_mcp_oauth_connection_state", "state IN (0, 1, 2, 3, 4, 5, 6) AND ((state IN (2, 3, 4) AND access_token_secret_id IS NOT NULL) OR (state NOT IN (2, 3, 4) AND access_token_secret_id IS NULL)) AND ((state IN (3, 4) AND refresh_token_secret_id IS NOT NULL AND refresh_attempt_id IS NOT NULL AND refresh_started_at IS NOT NULL) OR (state NOT IN (3, 4) AND refresh_attempt_id IS NULL AND refresh_started_at IS NULL))");
                        });
                });

            modelBuilder.Entity("Agentweaver.Identity.Broker.RemoteMcpOAuthConsentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthorizationEndpointUri")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("authorization_endpoint_uri");

                    b.Property<string>("BindingHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("binding_hash")
                        .IsFixedLength();

                    b.Property<Guid?>("ClaimAttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_attempt_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("ConnectionRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("connection_record_id");

                    b.Property<long>("ConnectionRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("connection_revision");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("PkceChallenge")
                        .IsRequired()
                        .HasMaxLength(43)
                        .HasColumnType("character varying(43)")
                        .HasColumnName("pkce_challenge");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<string>("StateHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("state_hash")
                        .IsFixedLength();

                    b.Property<string>("TokenEndpointUri")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("token_endpoint_uri");

                    b.Property<string>("VerifierSecretId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("verifier_secret_id");

                    b.Property<string>("VerifierSecretVersion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("verifier_secret_version");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionRecordId");

                    b.HasIndex("CorrelationId")
                        .IsUnique();

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("StateHash")
                        .IsUnique();

                    b.ToTable("remote_mcp_oauth_consents", "identity_broker", t =>
                        {
                            t.HasCheckConstraint("ck_remote_mcp_oauth_consent_challenge", "pkce_challenge ~ '^[A-Za-z0-9_-]{43}$'");

                            t.HasCheckConstraint("ck_remote_mcp_oauth_consent_hashes", "binding_hash ~ '^[0-9a-f]{64}$' AND state_hash ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("ck_remote_mcp_oauth_consent_revisions", "connection_revision > 0 AND revision > 0 AND expires_at > created_at");

                            t.HasCheckConstraint("ck_remote_mcp_oauth_consent_state", "state IN (0, 1, 2, 3, 4) AND ((state = 1 AND claim_attempt_id IS NOT NULL) OR (state <> 1 AND claim_attempt_id IS NULL))");
                        });
                });

            modelBuilder.Entity("Agentweaver.Identity.Broker.RepoAppAuthorizationTransaction", b =>
                {
                    b.Property<string>("StateHash")
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("state_hash")
                        .IsFixedLength();

                    b.Property<string>("CallbackCookieHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("callback_cookie_hash")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<long?>("InstallationId")
                        .HasColumnType("bigint")
                        .HasColumnName("installation_id");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("ProtectedCodeVerifier")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("protected_code_verifier");

                    b.Property<int>("Purpose")
                        .HasColumnType("integer")
                        .HasColumnName("purpose");

                    b.Property<string>("ReturnRouteKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("return_route_key");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("transaction_id");

                    b.HasKey("StateHash");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("OwnerId");

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.ToTable("repo_app_authorization_transactions", "identity_broker", t =>
                        {
                            t.HasCheckConstraint("ck_repo_app_authorization_state", "state IN (0, 1, 2, 3)");
                        });
                });

            modelBuilder.Entity("Agentweaver.Identity.Broker.RepoAppConnectionRecord", b =>
                {
                    b.Property<string>("ConnectionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("connection_id");

                    b.Property<DateTimeOffset>("AccessTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("access_token_expires_at");

                    b.Property<string>("AccessTokenSecretId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("access_token_secret_id");

                    b.Property<string>("AccessTokenSecretVersion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("access_token_secret_version");

                    b.Property<long>("ConnectionRevision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("connection_revision");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CredentialRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("credential_revision");

                    b.Property<string>("GitHubLogin")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("github_login");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateTimeOffset?>("RefreshLeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_lease_expires_at");

                    b.Property<Guid?>("RefreshLeaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("refresh_lease_id");

                    b.Property<DateTimeOffset>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expires_at");

                    b.Property<string>("RefreshTokenSecretId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("refresh_token_secret_id");

                    b.Property<string>("RefreshTokenSecretVersion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("refresh_token_secret_version");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ConnectionId");

                    b.HasIndex("OwnerId")
                        .IsUnique();

                    b.ToTable("repo_app_connections", "identity_broker", t =>
                        {
                            t.HasCheckConstraint("ck_repo_app_connection_refresh_lease", "(refresh_lease_id IS NULL) = (refresh_lease_expires_at IS NULL)");

                            t.HasCheckConstraint("ck_repo_app_connection_revisions", "connection_revision > 0 AND credential_revision > 0");

                            t.HasCheckConstraint("ck_repo_app_connection_state", "state IN (0, 1, 2)");
                        });
                });

            modelBuilder.Entity("Agentweaver.Identity.Broker.RepoAppInstallationRecord", b =>
                {
                    b.Property<string>("ConnectionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("connection_id");

                    b.Property<long>("InstallationId")
                        .HasColumnType("bigint")
                        .HasColumnName("installation_id");

                    b.Property<string>("AccountLogin")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("account_login");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("account_type");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<long>("ConnectionRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("connection_revision");

                    b.Property<string>("RepositorySelection")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("repository_selection");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.HasKey("ConnectionId", "InstallationId");

                    b.ToTable("repo_app_installations", "identity_broker", t =>
                        {
                            t.HasCheckConstraint("ck_repo_app_installation_identity", "installation_id > 0 AND connection_revision > 0");
                        });
                });

            modelBuilder.Entity("Agentweaver.Identity.Broker.RepoAppRepositorySelectionRecord", b =>
                {
                    b.Property<string>("CodeHash")
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("code_hash")
                        .IsFixedLength();

                    b.Property<string>("ConnectionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("connection_id");

                    b.Property<long>("ConnectionRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("connection_revision");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<long>("InstallationId")
                        .HasColumnType("bigint")
                        .HasColumnName("installation_id");

                    b.Property<bool>("IssueWriteRequested")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("issue_write_requested");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("PermissionDigest")
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("permission_digest")
                        .IsFixedLength();

                    b.Property<string>("ProjectId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("project_id");

                    b.Property<string>("RepositoryFullName")
                        .IsRequired()
                        .HasMaxLength(201)
                        .HasColumnType("character varying(201)")
                        .HasColumnName("repository_full_name");

                    b.Property<long>("RepositoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("repository_id");

                    b.HasKey("CodeHash");

                    b.HasIndex("ConnectionId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("OwnerId");

                    b.ToTable("repo_app_repository_selections", "identity_broker", t =>
                        {
                            t.HasCheckConstraint("ck_repo_app_selection_binding", "connection_revision > 0 AND installation_id > 0 AND repository_id > 0 AND expires_at > created_at");

                            t.HasCheckConstraint("ck_repo_app_selection_permission_digest", "permission_digest IS NULL OR permission_digest ~ '^[0-9a-f]{64}$'");
                        });
                });

            modelBuilder.Entity("Agentweaver.Identity.Broker.RuntimeGrantHead", b =>
                {
                    b.Property<Guid>("GrantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("grant_id");

                    b.Property<long>("CurrentRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("current_revision");

                    b.HasKey("GrantId");

                    b.ToTable("runtime_grant_heads", "identity_broker", t =>
                        {
                            t.HasCheckConstraint("ck_runtime_grant_heads_revision", "current_revision > 0");
                        });
                });

            modelBuilder.Entity("Agentweaver.Identity.Broker.RuntimeGrantOperation", b =>
                {
                    b.Property<Guid>("OperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<Guid>("GrantId")
                        .HasColumnType("uuid")
                        .HasColumnName("grant_id");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_hash");

                    b.HasKey("OperationId");

                    b.ToTable("runtime_grant_operations", "identity_broker");
                });

            modelBuilder.Entity("Agentweaver.Identity.Broker.RuntimeGrantOperationReceipt", b =>
                {
                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<string>("ReceiptJson")
                        .IsRequired()
                        .HasMaxLength(16384)
                        .HasColumnType("character varying(16384)")
                        .HasColumnName("receipt_json");

                    b.HasKey("OperationId");

                    b.ToTable("runtime_grant_operation_receipts", "identity_broker");
                });

            modelBuilder.Entity("Agentweaver.Identity.Broker.RuntimeGrantRevision", b =>
                {
                    b.Property<Guid>("GrantId")
                        .HasColumnType("uuid")
                        .HasColumnName("grant_id");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<string>("Audience")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("audience");

                    b.Property<string>("ConfigurationHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("configuration_hash");

                    b.Property<Guid>("DeliveryOperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("delivery_operation_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("issuer");

                    b.Property<int>("Purpose")
                        .HasColumnType("integer")
                        .HasColumnName("purpose");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<string>("RegistrationHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("registration_hash");

                    b.Property<string>("RegistrationJson")
                        .IsRequired()
                        .HasMaxLength(16384)
                        .HasColumnType("character varying(16384)")
                        .HasColumnName("registration_json");

                    b.Property<long>("RegistrationRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("registration_revision");

                    b.Property<Guid>("RuntimeInstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("runtime_instance_id");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<string>("VerifierHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("verifier_hash");

                    b.HasKey("GrantId", "Revision");

                    b.HasIndex("RuntimeInstanceId");

                    b.ToTable("runtime_grant_revisions", "identity_broker", t =>
                        {
                            t.HasCheckConstraint("ck_runtime_grant_hashes", "registration_hash ~ '^[0-9a-f]{64}$' AND verifier_hash ~ '^[0-9a-f]{64}$' AND configuration_hash ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("ck_runtime_grant_lifetime", "expires_at > recorded_at OR state = 2");

                            t.HasCheckConstraint("ck_runtime_grant_purpose", "purpose IN (0, 1)");

                            t.HasCheckConstraint("ck_runtime_grant_revision", "revision > 0 AND registration_revision > 0");

                            t.HasCheckConstraint("ck_runtime_grant_state", "state IN (0, 1, 2)");
                        });
                });

            modelBuilder.Entity("Agentweaver.Identity.Broker.SecretGrantHead", b =>
                {
                    b.Property<string>("GrantId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("grant_id");

                    b.Property<long>("CurrentRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("current_revision");

                    b.HasKey("GrantId");

                    b.ToTable("secret_grant_heads", "identity_broker", t =>
                        {
                            t.HasCheckConstraint("ck_secret_grant_heads_revision", "current_revision >= 0");
                        });
                });

            modelBuilder.Entity("Agentweaver.Identity.Broker.SecretGrantOperation", b =>
                {
                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("GrantId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("grant_id");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_hash");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.HasKey("IdempotencyKey");

                    b.ToTable("secret_grant_operations", "identity_broker");
                });

            modelBuilder.Entity("Agentweaver.Identity.Broker.SecretGrantRevision", b =>
                {
                    b.Property<string>("GrantId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("grant_id");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("project_id");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("purpose");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("run_id");

                    b.Property<string>("SecretId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("secret_id");

                    b.Property<string>("SecretVersion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("secret_version");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.HasKey("GrantId", "Revision");

                    b.HasIndex("ActorId", "ProjectId", "RunId");

                    b.ToTable("secret_grant_revisions", "identity_broker");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ApplicationType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ClientId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ClientSecret")
                        .HasColumnType("text");

                    b.Property<string>("ClientType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConsentType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("text");

                    b.Property<string>("JsonWebKeySet")
                        .HasColumnType("text");

                    b.Property<string>("Permissions")
                        .HasColumnType("text");

                    b.Property<string>("PostLogoutRedirectUris")
                        .HasColumnType("text");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<string>("RedirectUris")
                        .HasColumnType("text");

                    b.Property<string>("Requirements")
                        .HasColumnType("text");

                    b.Property<string>("Settings")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("OpenIddictApplications", "identity_broker");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<string>("Scopes")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type");

                    b.ToTable("OpenIddictAuthorizations", "identity_broker");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreScope", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Descriptions")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<string>("Resources")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("OpenIddictScopes", "identity_broker");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreToken", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("text");

                    b.Property<string>("AuthorizationId")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .HasColumnType("text");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RedemptionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Type")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationId");

                    b.HasIndex("ReferenceId")
                        .IsUnique();

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type");

                    b.ToTable("OpenIddictTokens", "identity_broker");
                });

            modelBuilder.Entity("Agentweaver.Identity.Broker.CopilotConnectionRevision", b =>
                {
                    b.HasOne("Agentweaver.Identity.Broker.CopilotConnectionRecord", null)
                        .WithMany()
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Agentweaver.Identity.Broker.RemoteMcpOAuthConnectionRecord", b =>
                {
                    b.HasOne("Agentweaver.Identity.Broker.BrokerUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Agentweaver.Identity.Broker.RemoteMcpOAuthConsentRecord", b =>
                {
                    b.HasOne("Agentweaver.Identity.Broker.RemoteMcpOAuthConnectionRecord", null)
                        .WithMany()
                        .HasForeignKey("ConnectionRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Agentweaver.Identity.Broker.RepoAppAuthorizationTransaction", b =>
                {
                    b.HasOne("Agentweaver.Identity.Broker.BrokerUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Agentweaver.Identity.Broker.RepoAppConnectionRecord", b =>
                {
                    b.HasOne("Agentweaver.Identity.Broker.BrokerUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Agentweaver.Identity.Broker.RepoAppInstallationRecord", b =>
                {
                    b.HasOne("Agentweaver.Identity.Broker.RepoAppConnectionRecord", null)
                        .WithMany()
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Agentweaver.Identity.Broker.RepoAppRepositorySelectionRecord", b =>
                {
                    b.HasOne("Agentweaver.Identity.Broker.RepoAppConnectionRecord", null)
                        .WithMany()
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Agentweaver.Identity.Broker.BrokerUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Agentweaver.Identity.Broker.RuntimeGrantOperationReceipt", b =>
                {
                    b.HasOne("Agentweaver.Identity.Broker.RuntimeGrantOperation", null)
                        .WithOne()
                        .HasForeignKey("Agentweaver.Identity.Broker.RuntimeGrantOperationReceipt", "OperationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Agentweaver.Identity.Broker.RuntimeGrantRevision", b =>
                {
                    b.HasOne("Agentweaver.Identity.Broker.RuntimeGrantHead", null)
                        .WithMany()
                        .HasForeignKey("GrantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Agentweaver.Identity.Broker.SecretGrantRevision", b =>
                {
                    b.HasOne("Agentweaver.Identity.Broker.SecretGrantHead", null)
                        .WithMany()
                        .HasForeignKey("GrantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", "Application")
                        .WithMany("Authorizations")
                        .HasForeignKey("ApplicationId");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreToken", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", "Application")
                        .WithMany("Tokens")
                        .HasForeignKey("ApplicationId");

                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", "Authorization")
                        .WithMany("Tokens")
                        .HasForeignKey("AuthorizationId");

                    b.Navigation("Application");

                    b.Navigation("Authorization");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", b =>
                {
                    b.Navigation("Authorizations");

                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
