#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { assertVersionMirrors, releaseBranchVersion, extractChangelogSection } from "./shared.mjs";
const root = process.cwd(); const expectedIndex = process.argv.indexOf("--expected"); const expected = expectedIndex >= 0 ? process.argv[expectedIndex + 1] : undefined;
if (!expected || !/^\d+\.\d+\.\d+$/.test(expected)) throw new Error("Use --expected X.Y.Z");
const git = (...args) => execFileSync("git", args, { cwd: root, encoding: "utf8" }).trim();
if (git("status", "--porcelain")) throw new Error("Working tree must be clean before release preparation.");
const branch = git("branch", "--show-current");
if (releaseBranchVersion(branch) !== expected) throw new Error(`release:prepare must run on release/v${expected}, not ${branch || "detached HEAD"}`);
assertVersionMirrors(root);
execFileSync(process.execPath, [path.join(root, "node_modules", "@changesets", "cli", "bin.js"), "version"], { cwd: root, stdio: "inherit" });
const pkg = JSON.parse(fs.readFileSync(path.join(root, "package.json"), "utf8"));
if (pkg.version !== expected) throw new Error(`Changesets calculated ${pkg.version}; expected ${expected}. Re-cut the release branch instead of forcing a version.`);
if (expected === "1.0.0" ? false : expected.split(".")[0] !== "0") throw new Error("Unexpected major-version transition.");
fs.writeFileSync(path.join(root, "VERSION"), `${expected}\n`);
assertVersionMirrors(root);
extractChangelogSection(fs.readFileSync(path.join(root, "CHANGELOG.md"), "utf8"), expected);
console.log(`Prepared v${expected}. Review VERSION, package.json, package-lock.json, CHANGELOG.md, and consumed .changeset files before committing.`);
