using System.Runtime.CompilerServices;
using System.Text.Json;
using Agentweaver.Api.Auth;
using Agentweaver.Tests.Helpers;
using FluentAssertions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http.Metadata;
using Microsoft.AspNetCore.Routing;
using Microsoft.Extensions.DependencyInjection;

namespace Agentweaver.Tests.Auth;

public sealed class EndpointAuthorizationInventoryTests : IDisposable
{
    private static readonly HashSet<string> OpenApiMethods =
        ["delete", "get", "head", "options", "patch", "post", "put", "trace"];

    private readonly AgentweaverWebApplicationFactory _factory = new();
    private readonly HttpClient _client;

    public EndpointAuthorizationInventoryTests() => _client = _factory.CreateClient();

    [Fact]
    public void EveryApplicationEndpoint_HasExactlyOneClassification_AndMatchesGoldenInventory()
    {
        var endpoints = GetRouteEndpoints();
        var applicationEndpoints = endpoints
            .Where(endpoint => endpoint.Metadata.GetMetadata<ApplicationEndpointMetadata>() is not null)
            .ToArray();
        applicationEndpoints.Should().NotBeEmpty();

        foreach (var endpoint in applicationEndpoints)
        {
            var classifications = endpoint.Metadata.GetOrderedMetadata<EndpointAuthorizationMetadata>();
            classifications.Should().ContainSingle(
                $"application endpoint '{endpoint.RoutePattern.RawText}' must declare exactly one authorization classification");

            var allowsAnonymous = endpoint.Metadata.GetMetadata<IAllowAnonymous>() is not null;
            allowsAnonymous.Should().Be(
                !classifications[0].RequiresBearerAuthentication,
                $"endpoint '{endpoint.RoutePattern.RawText}' must not use bare AllowAnonymous metadata");
        }

        var frameworkEndpoints = endpoints.Except(applicationEndpoints).ToArray();
        frameworkEndpoints
            .Where(endpoint =>
                endpoint.RoutePattern.RawText is null
                || !endpoint.RoutePattern.RawText.StartsWith("/openapi/", StringComparison.Ordinal))
            .Should().BeEmpty(
                "only framework-owned OpenAPI document endpoints are deliberately outside the application inventory");

        var actual = applicationEndpoints
            .SelectMany(endpoint => HttpMethods(endpoint).Select(method =>
                $"{method} {endpoint.RoutePattern.RawText} | " +
                endpoint.Metadata.GetRequiredMetadata<EndpointAuthorizationMetadata>().Kind))
            .Order(StringComparer.Ordinal)
            .ToArray();
        var goldenPath = GoldenPath();
        if (string.Equals(
                Environment.GetEnvironmentVariable("UPDATE_AUTH_ENDPOINT_GOLDEN"),
                "1",
                StringComparison.Ordinal))
        {
            File.WriteAllLines(
                goldenPath,
                ["# Generated by EndpointAuthorizationInventoryTests. Set UPDATE_AUTH_ENDPOINT_GOLDEN=1 to refresh.", .. actual]);
        }

        var expected = File.ReadAllLines(goldenPath)
            .Where(line => !line.StartsWith('#') && !string.IsNullOrWhiteSpace(line))
            .ToArray();
        actual.Should().Equal(expected);
    }

    [Fact]
    public async Task OpenApiBearerSecurity_MatchesRuntimeEndpointMetadata()
    {
        using var response = await _client.GetAsync("/openapi/v1.json");
        response.EnsureSuccessStatusCode();
        using var document = JsonDocument.Parse(await response.Content.ReadAsStringAsync());

        var metadataByOperation = GetRouteEndpoints()
            .Where(endpoint => endpoint.Metadata.GetMetadata<ApplicationEndpointMetadata>() is not null)
            .SelectMany(endpoint => HttpMethods(endpoint).Select(method => new
            {
                Key = $"{method.ToLowerInvariant()} {NormalizeOpenApiPath(endpoint.RoutePattern.RawText!)}",
                Authorization = endpoint.Metadata.GetRequiredMetadata<EndpointAuthorizationMetadata>(),
            }))
            .ToDictionary(item => item.Key, item => item.Authorization, StringComparer.Ordinal);

        foreach (var path in document.RootElement.GetProperty("paths").EnumerateObject())
        {
            foreach (var operation in path.Value.EnumerateObject().Where(property => OpenApiMethods.Contains(property.Name)))
            {
                var key = $"{operation.Name} {path.Name}";
                metadataByOperation.Should().ContainKey(key);
                var hasBearerSecurity = operation.Value.TryGetProperty("security", out var security)
                    && security.GetArrayLength() > 0;
                hasBearerSecurity.Should().Be(
                    metadataByOperation[key].RequiresBearerAuthentication,
                    $"OpenAPI operation '{key}' must derive security from its runtime endpoint metadata");
            }
        }
    }

    private RouteEndpoint[] GetRouteEndpoints() =>
        _factory.Services.GetRequiredService<EndpointDataSource>().Endpoints
            .OfType<RouteEndpoint>()
            .ToArray();

    private static IReadOnlyList<string> HttpMethods(RouteEndpoint endpoint) =>
        endpoint.Metadata.GetMetadata<IHttpMethodMetadata>()?.HttpMethods ?? ["*"];

    private static string NormalizeOpenApiPath(string routePattern) =>
        routePattern.Replace("{**", "{", StringComparison.Ordinal)
            .Replace("{*", "{", StringComparison.Ordinal);

    private static string GoldenPath([CallerFilePath] string sourcePath = "") =>
        Path.Combine(Path.GetDirectoryName(sourcePath)!, "EndpointAuthorization.golden.txt");

    public void Dispose()
    {
        _client.Dispose();
        _factory.Dispose();
    }
}
